# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ad64d837e683d4c199e743c4152c2a71c5200c0e036a839663d004670c4e4c99a1f41f62b970bd40a94f0a850f918a4f105d61169ccf1308b120beda774b4374

test:
  secret_key_base: 3f0955080aa1337d7ea0ee2753208467b799173ce658e3ffd17e94e40036418b5815c284eeb787bfe61cf7f219696fa63a4023f4f1bd6a209ae1e57297539422

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
